spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baidu-route
          uri: https://www.taobao.com
          predicates:
            - Query=url,taobao
        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
server:
  port: 88
